# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby 3.3.0-preview2
        run: |
          git clone https://github.com/rbenv/ruby-build.git
          PREFIX="$HOME/ruby-build" ./ruby-build/install.sh
          $HOME/ruby-build/bin/ruby-build 3.3.0-preview2 ~/.rbenv/versions/3.3.0-preview2
          echo "export PATH=$HOME/.rbenv/versions/3.3.0-preview2/bin:$PATH" >> $GITHUB_ENV

      - name: Install Bundler and cache gems
        run: |
          gem install bundler
          bundle config set --local path 'vendor/bundle'
          bundle install
          
      - name: Set up database schema
        run: bin/rails db:schema:load
        
      - name: Run tests
        run: bin/rake

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby 3.3.0-preview2
        run: |
          git clone https://github.com/rbenv/ruby-build.git
          PREFIX="$HOME/ruby-build" ./ruby-build/install.sh
          $HOME/ruby-build/bin/ruby-build 3.3.0-preview2 ~/.rbenv/versions/3.3.0-preview2
          echo "export PATH=$HOME/.rbenv/versions/3.3.0-preview2/bin:$PATH" >> $GITHUB_ENV

      - name: Install Bundler and cache gems
        run: |
          gem install bundler
          bundle config set --local path 'vendor/bundle'
          bundle install

      - name: Security audit dependencies
        run: bin/bundler-audit --update

      - name: Security audit application code
        run: bin/brakeman -q -w2

      - name: Lint Ruby files
        run: bin/rubocop --parallel
